import "@/styles/global/globals.css";
import "@/styles/global/fonts/chakraPetch.css";

import type { AppProps } from "next/app";
import Head from "next/head";
import ToastContainerComponent from "@/components/ToastContainer";

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <title>Mini Games</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
            <ToastContainerComponent />
        </>
    );
}
